[proton-game]
type = protondrive
username = ryan.khashayar@proton.me
password = cEPr7RZL1fg6N8C5fBwpGPgbG8GrqJUHZf20HBBKHW8d2cLHYw
2fa = 646144
description = my proton drive
client_uid = cfct6u2rxu2lqmnbhzj3lh2petkth3w3
client_access_token = fiih52ssxp5od2yvn5qoa7xoospnbjib
client_refresh_token = s7smhix37ku7ih5lrl7pnqvtrizgxg64
client_salted_key_pass = WVlXaFNDLlhNdHBzV1EyaXkyLi5BM2E1YkVMcTlZQw==

