[v1]
"cargo-audit 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-info 0.7.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-info"]
"cargo-machete 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-machete"]
"cargo-msrv 0.15.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-msrv"]
"cargo-tarpaulin 0.30.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tarpaulin"]
"cargo-update 13.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"sccache 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["sccache"]
"sqlx-cli 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-sqlx",
    "sqlx",
]
"trunk 0.20.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"wasm-bindgen-cli 0.2.92 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "wasm-bindgen",
    "wasm-bindgen-test-runner",
    "wasm2es6js",
]
