import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 28

opacity = 0.85
blur = true

decorations = "transparent"

[font]
normal.family = "JetBrainsMono Nerd Font Propo"
italic.family = "JetBrainsMono Nerd Font Propo"

size = 12.5
