echo ":::::::::::::::::::::::::::I:::::::::::::::::::::::::::::
::::::::::::::::::::::I<|jmx[-X}Xtjr(I::::::::::::::::::::
:::::::::::::::::|[nf]1vxr1?t{(•/(J)<J/<::::::::::::::::::
:::::::::::::lfXLfvvcrf|frnc1/nn)XCujxvX/r::::::::::::::::
:::::::::::IvzJ[CXXv/j1•!<+I!|!+j{jrxL[cc(x<::::::::::::::
:::::::::::Xr/LcuO?)|r+:I<:ll}I<U?/nr/|XXctjcI::::::::::::
::::::::::>CCvUctJ0i<(•]+lI!iI]i+)rnt)nfJtcczc::::::::::::
::::::::::I(juztu••ll:!>>+IIIIlln~fvLcvnccXxzc{:::::::::::
::::::::::IOLcXJ-1-l>il!]lIIII•l(-(xnjtr{trvLuXI::::::::::
:::::::::::LUJnfcI>++I?II!::I?Itj~xuzzzcurczc0x:::::::::::
::::::::::::xX/vunf><IlltUUr/+?>j[(jUUxrUuxJUnI:::::::::::
:::::::::::::vz>][Ii}<-iI}f~l>I<>}+JxvUO00UcC0::::::::::::
::::::::::::IzXLC/Zjj-III+ZOJf!I!}]xLJJCzCLJU:::::::::::::
::::::::::::v(Xn•il~z}:•IvzrIIII!!>?j0C0?>|J+:::::::::::::
::::::::::::r)fi-<ufnI:lII!!II!I:[-?LUCjcuUJ::::::::::::::
::::::::::::JO~jii(x(lI~l:!)li<I!{1xnLzcvu+f::::::::::::::
::::::::::::0C~|!<(uII:!1I-<lIiI!i!!Ur)<fn(U::::::::::::::
::::::::::::fv}xIlX0])LUfcf?lI>I•njfxfrfz?tI::::::::::::::
::::::::::::I|(]>1fX++Il!ll1ll+i/|(czm-{)1::::::::::::::::
:::::::::::::J}[rrx/l|II~I!iIijftxt(CUn{z:::::::::::::::::
:::::::::::::J(tu<0OUUOUCXz(1I]!]nXLZnCCI:::::::::::::::::
:::::::::::::l0Ux?u0zX)!l+I}<+{trXzCcmLI::::::::::::::::::
::::::::::::::LZjj0zrf{l!IIl<)(t}xCJ)(0XI:::::::::::::::::
:::::::::::::::LZxUn!l(>IlI•]<(|/xLxUJuv0:::::::::::::::::
::::::::::::::::COXt)i+~<~lr|nzXXLZnwClL0X::::::::::::::::
:::::::::::::::::lOOvCnun)vnuzzCCzvvn!ZzXZ0:::::::::::::::
:::::::::::::::::lzZ0OUzrcf)xfn0JrX}XZ0L0xCOCOI:::::::::::
:::::::::::::::::XmLLq0CCJUJffn[1ItzuvJ(cZZmJJO0O[::::::::
:::::::::::::]JwLmxZ0Ozvjjrf(]!OU/zZZXzLUmm0OXmO0L0Z?:::::
:::::::::cmZZmmjkqUOLm>cjU~!Zcuf0LCzCL0Oz0w0JuL0LO0JOXU:::
:::::{LmL00jmZjOOx)vZnOmULUUOmO0qCCJuXL0LwU0ZOX00ZwJ0m0O(:
::::::!tcL0qZUc0OXCZL0CLLLOCX1}/LLLCUuOCwC0OLOLLmCq0C0Cv[:
::::::::I[xOJmXwZw0Cm0J0CurUwwZunvuXzZOCmUCZnUZ00U0UvZc-I:
:::::::::::!}cLmJ0wZZZOXO0vvnCOZLOXOOX0uwUZLXZOLJc0Xzn~:::
::::::::::::::I+xvOm0pcOmqULZuUmCOmJm000C0mJvu0zJnc[i:::::
::::::::::::::::::I-tcCtnCCCOXvXcUJXJ0LJLzvXXnj{•l::::::::"
