import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 20

opacity = 0.95
blur = true

decorations = "transparent"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 12.5
